-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------- Tables ----------------------
-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------
AutodriveTables ={}
DestTable = {
	Info = { id = 'destination', title = 'Destinations', icon = 'map-location-dot', txt = 'Where do you want to go?', },
	Toggle = {
		Start = { id = 'start', title = 'Toggle Autodrive', icon = 'paper-plane', txt = 'Just Go'},
		Stop  = { id = 'stop', title = 'Stop Autodrive', icon = 'paper-plane', txt = 'Just Stop'},
	},
	Args = {
		Freeroam = { id = "freeroam", 				title = "Freeroam", 		icon = 'helmet-safety', },
		Waypoint = { id = "waypoint", 				title = "Waypoint", 		icon = 'helmet-safety', },
		Fuel     = { id = "fuel", 					title = "Fuel", 			icon = 'helmet-safety', },
		Blip     = { id = "blip", 					title = "Blip", 			icon = 'helmet-safety', txt = "Pick a BLIP any BLIP",},
		Tag      = { id = "tag", 					title = "Tag Vehicle", 		icon = 'helmet-safety', },
		Follow   = { id = "follow", 				title = "Follow", 			icon = 'helmet-safety', },
		Postal   = { id = "postal", 				title = "Postal", 			icon = 'helmet-safety', },
	},
}
StylesTable = {
	Info = { id = 'styles', title = 'Driving Styles', icon = 'car-burst', txt = "Don't get too crazy",},
	Args = {
		Safe       = { id = "Safe", 				title = "Safe", 			icon = 'helmet-safety', 		code = 411 },
		Code1      = { id = "Code1", 				title = "Code 1", 			icon = 'circle-exclamation', 	code = 283 },
		Code3      = { id = "Code3", 				title = "Code 3", 			icon = 'triangle-exclamation',	code = 787007 },
		Aggressive = { id = "Aggressive", 			title = "Aggressive", 		icon = 'gauge-high', 			code = 318 },
		Wreckless  = { id = "Wreckless", 			title = "Wreckless", 		icon = 'car-burst', 			code = 786988 },
		Follow     = { id = "Follow", 				title = "Follow", 			icon = 'helmet-safety', 		code = 262719 },
		Chase      = { id = "Chase", 				title = "Chase", 			icon = 'helmet-safety', 		code = 262685 },
		Custom     = { id = "Custom", 				title = "Custom", 			icon = 'keyboard', 				code = 0 },
	},
}
SpeedTable = {
	Info = { id = 'speed', title = 'Speed Settings', icon = 'gauge-high', txt = "Take it easy.. ",},
	Args = {
		PostedLimits = { id = "postedspeed", 		title = "Posted Limits", 	icon = 'helmet-safety', },
		SetSpeed     = { id = "setspeed", 			title = "Set Speed", 	 	icon = 'helmet-safety', },
		ResetSpeed   = { id = "resetspeed", 		title = "Reset Speed", 	 	icon = 'helmet-safety', },
	},
}

SettingsTable = {
	Info = { id = 'settings', title = 'Autodrive Settings', icon = 'wrench', txt = "Fine Tuning",},
	Args = {
		OSD           	= { id = "osd", 			title = "OSD on/off", 		icon = 'car-on', txt = 'Heads Up!'},
		ToggleOsd     	= { id = "toggleosd", 		title = "OSD Always on/off",icon = 'car-on', },
		TimedOsd      	= { id = "timedosd", 		title = "Timed OSD", 		icon = 'clock', },
		SetSpeedUnits 	= { id = "setspeedunits", 	title = "Toggle mph/kmh", 	icon = 'ruler', },
		DriverCreate 	= { id = "drivercreate", 	title = "Driver Creation", 	icon = 'ruler', },
		DriverForced 	= { id = "driverforced", 	title = "Driver Forced", 	icon = 'ruler', },
		DriverVisible 	= { id = "drivervisible", 	title = "Driver Visiblity", icon = 'ruler', },
		-- Start 			= { id = "start", 			title = "Toggle Autodrive", icon = 'paper-plane', },
		-- Stop 			= { id = "stop", 			title = "Stop", 			icon = 'paper-plane', },
	},
}

QBMenuTable = {
	Info = { id = 'main', title = 'Autodrive Menu', icon = 'wrench', },
	Args = {
		OSD           	= { id = "osd", 			title = "OSD on/off", 		icon = 'car-on', },
		ToggleOsd     	= { id = "toggleosd", 		title = "Toggle OSD", 		icon = 'car-on', },
		TimedOsd      	= { id = "timedosd", 		title = "Timed OSD", 		icon = 'clock', },
		SetSpeedUnits 	= { id = "setspeedunits", 	title = "Toggle mph/kmh", 	icon = 'ruler', },
		DriverCreation 	= { id = "drivercreate", 	title = "Driver Creation", 	icon = 'ruler', },
		DriverForced 	= { id = "driverforced", 	title = "Driver Forced", 	icon = 'ruler', },
		DriverVisible 	= { id = "drivervisible", 	title = "Driver Visiblity", icon = 'ruler', },
	},
}


EventsTable = {
	Start = 'ta-autodrive:client:startautodrive',
	Stop = 'ta-autodrive:client:stopautodrive',
	Destination = {
		name = 'ta-autodrive:client:destination',
		Args = DestTable.Args,
	},
	Speed = {
		name = 'ta-autodrive:client:speed',
		Args = SpeedTable.Args,
	},
	Style = {
		name = 'ta-autodrive:client:style',
		Args = StylesTable.Args,
	},
	Settings = {
		name = 'ta-autodrive:client:settings',
		Args = SettingsTable.Args,
	},
	QBMenu = {
		main = 'ta-autodrive:client:qbmenu:main',
		Submenu = {
			name = 'ta-autodrive:client:qbmenu:submenu',
			Args = {
				'destinations',
				'styles',
				'speed',
				'blips',
			},
		},
		close = 'ta-autodrive:client:qbmenu:closemenu'
	}
}

ADItems = {
    ad_darts        = "ad_darts",
    ad_destinations = "ad_destinations",
    ad_fob          = "ad_fob",
    ad_kit          = "ad_kit",
    ad_osd          = "ad_osd",
    ad_speed        = "ad_speed",
    ad_styles       = "ad_styles",
    ad_tagger       = "ad_tagger",

}

Values = {
    ["Safe"]       = 411,
    ["Code1"]      = 283,
    ["Aggressive"] = 318,
    ["Wreckless"]  = 786988,
    ["Code3"]      = 787007,
    ["Chase"]      = 262685,
    ["Follow"]     = 262719,
    ["Custom"]     = ChosenDrivingStyle,
}

AreaNames = {
    AIRP      = 'Los Santos International Airport',
    ALAMO     = 'Alamo Sea',
    ALTA      = 'Alta',
    ARMYB     = 'Fort Zancudo',
    BANHAMC   = 'Banham Canyon Dr',
    BANNING   = 'Banning',
    BEACH     = 'Vespucci Beach',
    BHAMCA    = 'Banham Canyon',
    BRADP     = 'Braddock Pass',
    BRADT     = 'Braddock Tunnel',
    BURTON    = 'Burton',
    CALAFB    = 'Calafia Bridge',
    CANNY     = 'Raton Canyon',
    CCREAK    = 'Cassidy Creek',
    CHAMH     = 'Chamberlain Hills',
    CHIL      = 'Vinewood Hills',
    CHU       = 'Chumash',
    CMSW      = 'Chiliad Mountain State Wilderness',
    CYPRE     = 'Cypress Flats',
    DAVIS     = 'Davis',
    DELBE     = 'Del Perro Beach',
    DELPE     = 'Del Perro',
    DELSOL    = 'La Puerta',
    DESRT     = 'Grand Senora Desert',
    DOWNT     = 'Downtown',
    DTVINE    = 'Downtown Vinewood',
    EAST_V    = 'East Vinewood',
    EBURO     = 'El Burro Heights',
    ELGORL    = 'El Gordo Lighthouse',
    ELYSIAN   = 'Elysian Island',
    GALFISH   = 'Galilee',
    GOLF      = 'GWC and Golfing Society',
    GRAPES    = 'Grapeseed',
    GREATC    = 'Great Chaparral',
    HARMO     = 'Harmony',
    HAWICK    = 'Hawick',
    HORS      = 'Vinewood Racetrack',
    HUMLAB    = 'Humane Labs and Research',
    JAIL      = 'Bolingbroke Penitentiary',
    KOREAT    = 'Little Seoul',
    LACT      = 'Land Act Reservoir',
    LAGO      = 'Lago Zancudo',
    LDAM      = 'Land Act Dam',
    LEGSQU    = 'Legion Square',
    LMESA     = 'La Mesa',
    LOSPUER   = 'La Puerta',
    MIRR      = 'Mirror Park',
    MORN      = 'Morningwood',
    MOVIE     = 'Richards Majestic',
    MTCHIL    = 'Mount Chiliad',
    MTGORDO   = 'Mount Gordo',
    MTJOSE    = 'Mount Josiah',
    MURRI     = 'Murrieta Heights',
    NCHU      = 'North Chumash',
    NOOSE     = 'N.O.O.S.E',
    OCEANA    = 'Pacific Ocean',
    PALCOV    = 'Paleto Cove',
    PALETO    = 'Paleto Bay',
    PALFOR    = 'Paleto Forest',
    PALHIGH   = 'Palomino Highlands',
    PALMPOW   = 'Palmer-Taylor Power Station',
    PBLUFF    = 'Pacific Bluffs',
    PBOX      = 'Pillbox Hill',
    PROCOB    = 'Procopio Beach',
    RANCHO    = 'Rancho',
    RGLEN     = 'Richman Glen',
    RICHM     = 'Richman',
    ROCKF     = 'Rockford Hills',
    RTRAK     = 'Redwood Lights Track',
    SANAND    = 'San Andreas',
    SANCHIA   = 'San Chianski Mountain Range',
    SANDY     = 'Sandy Shores',
    SKID      = 'Mission Row',
    SLAB      = 'Stab City',
    STAD      = 'Maze Bank Arena',
    STRAW     = 'Strawberry',
    TATAMO    = 'Tataviam Mountains',
    TERMINA   = 'Terminal',
    TEXTI     = 'Textile City',
    TONGVAH   = 'Tongva Hills',
    TONGVAV   = 'Tongva Valley',
    VCANA     = 'Vespucci Canals',
    VESP      = 'Vespucci',
    VINE      = 'Vinewood',
    WINDF     = 'Ron Alternates Wind Farm',
    WVINE     = 'West Vinewood',
    ZANCUDO   = 'Zancudo River',
    ZP_ORT    = 'Port of South Los Santos',
    ZQ_UAR    = 'Davis Quartz',
    PROL      = 'Prologue / North Yankton',
    ISHeist   = 'Cayo Perico Island',
}

local speedLimits = {}
Street = {}

if ADDefaults.UseMPH then
    speedLimits = {
    s0 = 20.0,
    s1 = 20.0,
    s2 = 25.0,
    s3 = 30.0,
    s4 = 35.0,
    s5 = 40.0,
    s6 = 45.0,
    s7 = 50.0,
    s8 = 65.0,
    s9 = 70.0,
    }
else
    speedLimits = {
        s0 = 32.0,
        s1 = 32.0,
        s2 = 40.0,
        s3 = 48.0,
        s4 = 56.0,
        s5 = 64.0,
        s6 = 72.0,
        s7 = 80.0,
        s8 = 104.0,
        s9 = 112.0,
    }
end

Street.Speed = {
    ["Abattoir Ave"]              = speedLimits.s3,
    ["Abe Milton Pkwy"]           = speedLimits.s3,
    ["Ace Jones Dr"]              = speedLimits.s3,
    ["Adam's Apple Blvd"]         = speedLimits.s4,
    ["Aguja St"]                  = speedLimits.s1,
    ["Algonquin Blvd"]            = speedLimits.s3,
    ["Alhambra Dr"]               = speedLimits.s3,
    ["Alta Pl"]                   = speedLimits.s2,
    ["Alta St"]                   = speedLimits.s4,
    ["Amarillo Vista"]            = speedLimits.s1,
    ["Amarillo Way"]              = speedLimits.s3,
    ["Americano Way"]             = speedLimits.s1,
    ["Armadillo Ave"]             = speedLimits.s3,
    ["Atlee St"]                  = speedLimits.s2,
    ["Autopia Pkwy"]              = speedLimits.s3,
    ["Banham Canyon Dr"]          = speedLimits.s4,
    ["Barbareno Rd"]              = speedLimits.s2,
    ["Bay City Ave"]              = speedLimits.s2,
    ["Bay City Incline"]          = speedLimits.s4,
    ["Baytree Canyon Rd"]         = speedLimits.s4,
    ["Boulevard Del Perro"]       = speedLimits.s3,
    ["Bridge St"]                 = speedLimits.s3,
    ["Brouge Ave"]                = speedLimits.s2,
    ["Buccaneer Way"]             = speedLimits.s6,
    ["Buen Vino Rd"]              = speedLimits.s4,
    ["Caesars Place"]             = speedLimits.s1,
    ["Calafia Rd"]                = speedLimits.s2,
    ["Calais Ave"]                = speedLimits.s3,
    ["Capital Blvd"]              = speedLimits.s2,
    ["Carcer Way"]                = speedLimits.s4,
    ["Carson Ave"]                = speedLimits.s3,
    ["Cascabel Ave"]              = speedLimits.s2,
    ["Cassidy Trail"]             = speedLimits.s1,
    ["Cat-Claw Ave"]              = speedLimits.s3,
    ["Catfish View"]              = speedLimits.s3,
    ["Cavalry Blvd"]              = speedLimits.s3,
    ["Chianski Passage"]          = speedLimits.s2,
    ["Cholla Rd"]                 = speedLimits.s3,
    ["Cholla Springs Ave"]        = speedLimits.s3,
    ["Chum St"]                   = speedLimits.s4,
    ["Chupacabra St"]             = speedLimits.s2,
    ["Clinton Ave"]               = speedLimits.s3,
    ["Cockingend Dr"]             = speedLimits.s3,
    ["Conquistador St"]           = speedLimits.s1,
    ["Cortes St"]                 = speedLimits.s1,
    ["Cougar Ave"]                = speedLimits.s2,
    ["Covenant Ave"]              = speedLimits.s2,
    ["Cox Way"]                   = speedLimits.s3,
    ["Crusade Rd"]                = speedLimits.s2,
    ["Davis Ave"]                 = speedLimits.s4,
    ["Decker St"]                 = speedLimits.s3,
    ["Del Perro Fwy"]             = speedLimits.s8,
    ["Didion Dr"]                 = speedLimits.s3,
    ["Dorset Dr"]                 = speedLimits.s4,
    ["Duluoz Ave"]                = speedLimits.s3,
    ["Dunstable Dr"]              = speedLimits.s3,
    ["Dunstable Ln"]              = speedLimits.s3,
    ["Dutch London St"]           = speedLimits.s4,
    ["East Galileo Ave"]          = speedLimits.s3,
    ["East Joshua Road"]          = speedLimits.s6,
    ["East Mirror Dr"]            = speedLimits.s3,
    ["Eastbourne Way"]            = speedLimits.s2,
    ["Eclipse Blvd"]              = speedLimits.s3,
    ["Edwood Way"]                = speedLimits.s1,
    ["El Burro Blvd"]             = speedLimits.s3,
    ["El Rancho Blvd"]            = speedLimits.s4,
    ["Elgin Ave"]                 = speedLimits.s4,
    ["Elysian Fields Fwy"]        = speedLimits.s6,
    ["Equality Way"]              = speedLimits.s2,
    ["Exceptionalists Way"]       = speedLimits.s3,
    ["Fenwell Pl"]                = speedLimits.s3,
    ["Fort Zancudo Approach Rd"]  = speedLimits.s1,
    ["Forum Dr"]                  = speedLimits.s3,
    ["Fudge Ln"]                  = speedLimits.s1,
    ["Galileo Park"]              = speedLimits.s3,
    ["Galileo Rd"]                = speedLimits.s4,
    ["Gentry Lane"]               = speedLimits.s2,
    ["Ginger St"]                 = speedLimits.s2,
    ["Glory Way"]                 = speedLimits.s3,
    ["Goma St"]                   = speedLimits.s1,
    ["Grapeseed Ave"]             = speedLimits.s3,
    ["Grapeseed Main St"]         = speedLimits.s3,
    ["Great Ocean Hwy"]           = speedLimits.s8,
    ["Greenwich Pkwy"]            = speedLimits.s3,
    ["Greenwich Pl"]              = speedLimits.s3,
    ["Greenwich Way"]             = speedLimits.s3,
    ["Grove St"]                  = speedLimits.s2,
    ["Hanger Way"]                = speedLimits.s2,
    ["Hangman Ave"]               = speedLimits.s3,
    ["Hardy Way"]                 = speedLimits.s3,
    ["Hawick Ave"]                = speedLimits.s3,
    ["Heritage Way"]              = speedLimits.s3,
    ["Hillcrest Ave"]             = speedLimits.s3,
    ["Hillcrest Ridge Access Rd"] = speedLimits.s3,
    ["Imagination Ct"]            = speedLimits.s1,
    ["Ineseno Road"]              = speedLimits.s2,
    ["Innocence Blvd"]            = speedLimits.s4,
    ["Integrity Way"]             = speedLimits.s2,
    ["Invention Ct"]              = speedLimits.s1,
    ["Jamestown St"]              = speedLimits.s2,
    ["Joad Ln"]                   = speedLimits.s3,
    ["Joshua Rd"]                 = speedLimits.s6,
    ["Kimble Hill Dr"]            = speedLimits.s3,
    ["Kortz Dr"]                  = speedLimits.s2,
    ["La Puerta Fwy"]             = speedLimits.s8,
    ["Labor Pl"]                  = speedLimits.s3,
    ["Laguna Pl"]                 = speedLimits.s2,
    ["Lake Vinewood Dr"]          = speedLimits.s3,
    ["Lake Vinewood Est"]         = speedLimits.s3,
    ["Las Lagunas Blvd"]          = speedLimits.s4,
    ["Lesbos Ln"]                 = speedLimits.s3,
    ["Liberty St"]                = speedLimits.s2,
    ["Lindsay Circus"]            = speedLimits.s2,
    ["Little Bighorn Ave"]        = speedLimits.s3,
    ["Lolita Ave"]                = speedLimits.s3,
    ["Los Santos Freeway"]        = speedLimits.s8,
    ["Low Power St"]              = speedLimits.s3,
    ["Macdonald St"]              = speedLimits.s3,
    ["Mad Wayne Thunder Dr"]      = speedLimits.s3,
    ["Magellan Ave"]              = speedLimits.s1,
    ["Marathon Ave"]              = speedLimits.s2,
    ["Marina Dr"]                 = speedLimits.s3,
    ["Marlowe Dr"]                = speedLimits.s4,
    ["Melanoma St"]               = speedLimits.s1,
    ["Meringue Ln"]               = speedLimits.s3,
    ["Meteor St"]                 = speedLimits.s2,
    ["Milton Rd"]                 = speedLimits.s3,
    ["Miriam Turner Overpass"]    = speedLimits.s2,
    ["Mirror Park Blvd"]          = speedLimits.s3,
    ["Mirror Pl"]                 = speedLimits.s3,
    ["Morningwood Blvd"]          = speedLimits.s3,
    ["Mountain View Dr"]          = speedLimits.s3,
    ["Movie Star Way"]            = speedLimits.s3,
    ["Mt Haan Rd"]                = speedLimits.s4,
    ["Mt Vinewood Dr"]            = speedLimits.s4,
    ["Mutiny Rd"]                 = speedLimits.s3,
    ["New Empire Way"]            = speedLimits.s2,
    ["Nikola Ave"]                = speedLimits.s3,
    ["Nikola Pl"]                 = speedLimits.s1,
    ["Niland Ave"]                = speedLimits.s3,
    ["Normandy Dr"]               = speedLimits.s3,
    ["North Calafia Way"]         = speedLimits.s2,
    ["North Conker Ave"]          = speedLimits.s3,
    ["North Rockford Dr"]         = speedLimits.s3,
    ["North Sheldon Ave"]         = speedLimits.s3,
    ["Nowhere Rd"]                = speedLimits.s1,
    ["O'Neil Way"]                = speedLimits.s1,
    ["Occupation Ave"]            = speedLimits.s3,
    ["Olympic Fwy"]               = speedLimits.s8,
    ["Orchardville Ave"]          = speedLimits.s2,
    ["Paleto Blvd"]               = speedLimits.s3,
    ["Palomino Ave"]              = speedLimits.s3,
    ["Palomino Fwy"]              = speedLimits.s8,
    ["Panorama Dr"]               = speedLimits.s4,
    ["Perth St"]                  = speedLimits.s1,
    ["Picture Perfect Drive"]     = speedLimits.s3,
    ["Plaice Pl"]                 = speedLimits.s2,
    ["Playa Vista"]               = speedLimits.s2,
    ["Popular St"]                = speedLimits.s4,
    ["Portola Dr"]                = speedLimits.s2,
    ["Power St"]                  = speedLimits.s4,
    ["Procopio Dr"]               = speedLimits.s3,
    ["Procopio Promenade"]        = speedLimits.s1,
    ["Prosperity St"]             = speedLimits.s2,
    ["Pyrite Ave"]                = speedLimits.s2,
    ["Red Desert Ave"]            = speedLimits.s2,
    ["Richman St"]                = speedLimits.s3,
    ["Rockford Dr"]               = speedLimits.s3,
    ["Route 68 Approach"]         = speedLimits.s7,
    ["Route 68"]                  = speedLimits.s7,
    ["Roy Lowenstein Blvd"]       = speedLimits.s3,
    ["Rub St"]                    = speedLimits.s1,
    ["Runway1"]                   = speedLimits.s9,
    ["Sam Austin Dr"]             = speedLimits.s1,
    ["San Andreas Ave"]           = speedLimits.s4,
    ["San Vitus Blvd"]            = speedLimits.s4,
    ["Sandcastle Way"]            = speedLimits.s2,
    ["Seaview Rd"]                = speedLimits.s3,
    ["Senora Fwy"]                = speedLimits.s8,
    ["Senora Rd"]                 = speedLimits.s4,
    ["Senora Way"]                = speedLimits.s4,
    ["Shank St"]                  = speedLimits.s1,
    ["Signal St"]                 = speedLimits.s2,
    ["Sinner St"]                 = speedLimits.s2,
    ["Sinners Passage"]           = speedLimits.s2,
    ["Smoke Tree Rd"]             = speedLimits.s3,
    ["South Arsenal St"]          = speedLimits.s3,
    ["South Boulevard Del Perro"] = speedLimits.s3,
    ["South Mo Milton Dr"]        = speedLimits.s3,
    ["South Rockford Dr"]         = speedLimits.s3,
    ["South Shambles St"]         = speedLimits.s2,
    ["Spanish Ave"]               = speedLimits.s2,
    ["Strawberry Ave"]            = speedLimits.s4,
    ["Supply St"]                 = speedLimits.s2,
    ["Sustancia Rd"]              = speedLimits.s6,
    ["Swiss St"]                  = speedLimits.s2,
    ["Tackle St"]                 = speedLimits.s1,
    ["Tongva Dr"]                 = speedLimits.s4,
    ["Tower Way"]                 = speedLimits.s3,
    ["Tug St"]                    = speedLimits.s1,
    ["Union Rd"]                  = speedLimits.s4,
    ["Utopia Gardens"]            = speedLimits.s1,
    ["Vespucci Blvd"]             = speedLimits.s4,
    ["Vinewood Blvd"]             = speedLimits.s4,
    ["Vinewood Park Dr"]          = speedLimits.s3,
    ["Vitus St"]                  = speedLimits.s1,
    ["Voodoo Place"]              = speedLimits.s2,
    ["West Eclipse Blvd"]         = speedLimits.s3,
    ["West Galileo Ave"]          = speedLimits.s3,
    ["West Mirror Drive"]         = speedLimits.s3,
    ["Whispymound Dr"]            = speedLimits.s3,
    ["Wild Oats Dr"]              = speedLimits.s3,
    ["Zancudo Ave"]               = speedLimits.s3,
    ["Zancudo Barranca"]          = speedLimits.s4,
    ["Zancudo Grande Valley"]     = speedLimits.s4,
    ["Zancudo Rd"]                = speedLimits.s3,
}